Fix: Use DDP for PPO traning will cause `AttributeError: 'DistributedDataParallel' object has no attribute 'policy'` (#5287)
* fix: ppo ddp

* ref: use accelerator.unwrap_model